### ISSUE TITLE
clusterctl pivots to internal cluster, make this optional

### ISSUE THREAD

**Issue by oneilcin** [kubernetes-sigs/cluster-api#450] opened 2018-07-25 18:02 UTC
In our use case we would like to use an external cluster other than minikube to deploy the cluster-api stack.  This external cluster will manage multiple clusters.  We would like to keep the controllers and cluster-api resources (machines, machineset, cluster, etc) on the external cluster.

The default behavior of clusterctl is to pivot the controllers and resources to the internal cluster.  We would like to make the pivoting optional, @timothysc prefers that we do not pivot by default.

**Comment by oneilcin** [comment] 2018-07-25 18:13
I would be glad to work on this

**Comment by hardikdr** [comment] 2018-07-26 11:56
I would also prefer not to pivot by default. 
It would actually be nice if we can inject kubeConfig of existing cluster where we keep the cluster-api stack and not necessarily depend on Minikube.

**Comment by oneilcin** [comment] 2018-07-26 14:56
Realized if clusterctl is used to deploy the managing cluster only, then the change is not needed for our use-case.  The created cluster would be the managing cluster of other clusters.  Then we could use kubectl or api calls to create the cluster and machines resources for adding new clusters.

**Comment by detiber** [comment] 2018-07-26 21:19
I'm planning on starting to look at this tomorrow.

**Comment by roberthbailey** [comment] 2018-08-17 21:32
Is this a specialization of the more general issue described in https://github.com/kubernetes-sigs/cluster-api/issues/479? Can we consolidate work around making the cluster creation pluggable?

**Comment by timothysc** [comment] 2019-01-11 20:12
This is a dupe of #554 #479

**Closed by timothysc** 2019-01-11 20:12 UTC
