### ISSUE TITLE
Solution for clusterctl commands when minikube already exists

### ISSUE THREAD

**Issue by spew** [kubernetes-sigs/cluster-api#413] opened 2018-06-29 17:06 UTC
As noted in PR https://github.com/kubernetes-sigs/cluster-api/pull/406#discussion_r199217893, when running `clusterctl create cluster` and `clusterctl delete cluster` the commands will fail if the minikube VM already exists. This can be fixed by running `minikube delete`. 

The purpose of this issue is to come up with a solution for this problem. Some potential solutions:

1. Automatically delete the machine every time.
2. If the machine exists, prompt the user and ask them to confirm and then delete.
3. Attempt to use the existing machine.
4. ???

**Comment by craigbox** [comment] 2018-07-07 17:07
Having been confused by this today (and tbh confused as to why it instantiates minikube and doesn't just take a cluster endpoint as configuration), I'd vote for 3 - with the proviso that (in the Alpha stage) if the apiserver extension exists, or there are cluster/machine objects, then you could abort and say 'please delete it before continuing'.

**Comment by davidewatson** [comment] 2019-01-11 01:34
What about using the `--existing-bootstrap-cluster-kubeconfig` option to point `clusterctl create cluster` to the existing minikube cluster?

**Comment by vincepri** [comment] 2019-01-11 20:35
I cannot reproduce this locally with the latest version of minikube and clusterctl. If I have minikube running, clusterctl will run `minikube start --bootstrapper=kubeadm` which re-initializes the cluster.

I'm gonna go ahead and close it, feel free to reopen if necessary.

/close

**Closed by vincepri** 2019-01-11 20:35 UTC
Labels: kind/clusterctl, priority/important-soon
