### ISSUE TITLE
v1.3.3 machineset_types.go using old k8s.io/apimachinery/pkg/apis/meta/v1/validation/ValidateLabelSelector signature

### ISSUE THREAD

**Issue by jluhrsen** [kubernetes-sigs/cluster-api#8167] opened 2023-02-23 23:58 UTC
**What steps did you take and what happened:**
[v1.3.3](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.3.3) is supposed to have caught up to [k8s 1.26]

but, [machineset_types.go](https://github.com/kubernetes-sigs/cluster-api/blob/09030092bf1e9891da4cf6b48b486cb76efaab82/api/v1beta1/machineset_types.go#L184) is still using the [v1.25 signature](https://github.com/kubernetes/apimachinery/blob/11eb99b88eea33b91648fa0445d364ba8b857bb8/pkg/apis/meta/v1/validation/validation.go#L31) for ValidateLabelSelector instead of the changed [v1.26 signature](https://github.com/kubernetes/apimachinery/blob/53ecdf01b997ca93c7db7615dfe7b27ad8391983/pkg/apis/meta/v1/validation/validation.go#L56)

the [HEAD of main](https://github.com/kubernetes-sigs/cluster-api/blob/193f13af38f729d04627f2dd1352a606028b0714/api/v1beta1/machineset_types.go#L184) in cluster-api is using the correct signature.

so, using a project that updates to cluster-api v1.3.3 and also tries to bump apimachinery to v1.26 will
break if it's using that function.

**What did you expect to happen:**

the new signature should be used. 

/kind bug

**Comment by sbueringer** [comment] 2023-02-24 04:18
Cluster API v1.3.3 added support for running on 1.26 mangement clusters and managing v1.26 workload clusters.

We never bump the controller-runtime / client-go minor version of Cluster API in a patch release as we consider this a breaking change.

**Comment by fabriziopandini** [comment] 2023-02-24 21:20
Rif to a doc explaining what @sbueringer said in more details https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-cycle.md

I'm closing this issue as it is not a bug but just a consequence of how we operate, which in this case is also conditioned by our dependency on controller runtime.

Feel free to re-open if you want more clarifications.
/close

**Closed by fabriziopandini** 2023-02-24 21:20 UTC
Labels: kind/bug, needs-triage

**Comment by jluhrsen** [comment] 2023-02-28 01:57
thanks for the clarifications.

**Comment by cwrau** [comment] 2023-04-24 11:35
We've also run into this problem, wanting to use `controller-runtime@v0.14.0` and also `cluster-api@v1.3.3`.

Is there a timeline when the controller-runtime will be bumped?

**Comment by killianmuldoon** [comment] 2023-04-24 11:41
@cwrau CAPI `v1.3.X` will not be bumped to controller runtime `v0.14.X` - as this would be considered a breaking change which can't be done on a patch release. If you'd like to use `v0.14.X` you can update to CAPI `v1.4.X`.

**Comment by sbueringer** [comment] 2023-04-24 12:33
CAPI is basically doing the same as Kubernetes in the sense that we have breaking changes like that in our minor releases
