### ISSUE TITLE
annoying error message "failed to update CoreDNS deployment: failed to validate CoreDNS:"

### ISSUE THREAD

**Issue by moonek** [kubernetes-sigs/cluster-api#2838] opened 2020-04-01 08:48 UTC
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

The log below is continuously output in `capi-kubeadm-control-plane-controller-manager`
(even after the workload cluster is successfully installed)
```
E0401 08:31:51.835866       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to update CoreDNS deployment: failed to validate CoreDNS: toVersion \"1.6.5\" must be greater than fromVersion \"1.6.5\""  "controller"="kubeadmcontrolplane" "request"={"Namespace":"default","Name":"vsphere-quickstart"}
E0401 08:32:35.274711       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to update CoreDNS deployment: failed to validate CoreDNS: toVersion \"1.6.5\" must be greater than fromVersion \"1.6.5\""  "controller"="kubeadmcontrolplane" "request"={"Namespace":"default","Name":"vsphere-quickstart"}
E0401 08:34:55.967563       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to update CoreDNS deployment: failed to validate CoreDNS: toVersion \"1.6.5\" must be greater than fromVersion \"1.6.5\""  "controller"="kubeadmcontrolplane" "request"={"Namespace":"default","Name":"vsphere-quickstart"}
E0401 08:41:47.723996       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to update CoreDNS deployment: failed to validate CoreDNS: toVersion \"1.6.5\" must be greater than fromVersion \"1.6.5\""  "controller"="kubeadmcontrolplane" "request"={"Namespace":"default","Name":"vsphere-quickstart"}
E0401 08:41:47.985904       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to update CoreDNS deployment: failed to validate CoreDNS: toVersion \"1.6.5\" must be greater than fromVersion \"1.6.5\""  "controller"="kubeadmcontrolplane" "request"={"Namespace":"default","Name":"vsphere-quickstart"}
E0401 08:43:03.570944       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to update CoreDNS deployment: failed to validate CoreDNS: toVersion \"1.6.5\" must be greater than fromVersion \"1.6.5\""  "controller"="kubeadmcontrolplane" "request"={"Namespace":"default","Name":"vsphere-quickstart"}
```

**What did you expect to happen:**
I know there is no need to update because the valid version and the current version are the same.
But why is the error level log constantly being output?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.3.3

/kind bug

**Comment by vincepri** [comment] 2020-04-01 15:21
This issue is the same as #2824, it should be fixed soon in v0.3.4

**Comment by vincepri** [comment] 2020-04-01 15:56
cc @gab-satchi

**Comment by vincepri** [comment] 2020-04-01 17:49
Closing as duplicate of #2810, feel free to reopen if necessary after v0.3.4 is released

/close

**Closed** 2020-04-01 17:49 UTC
Labels: kind/bug
