### ISSUE TITLE
flaking test: Machines should remain the same after the upgrade

### ISSUE THREAD

**Issue by aniruddha2000** [kubernetes-sigs/cluster-api#8101] opened 2023-02-13 14:01 UTC
##### Error text:
```
Failed after 30.070s.
Machines should remain the same after the upgrade
Expected
    <bool>: false
to be true
[FAILED] Failed after 30.070s.
Machines should remain the same after the upgrade
Expected
    <bool>: false
to be true
In [It] at: /home/prow/go/src/sigs.k8s.io/cluster-api/test/e2e/clusterctl_upgrade.go:451 @ 02/03/23 01:33:29.995

```
#### Recent failures:
[13/2/2023, 6:30:02 pm periodic-cluster-api-e2e-mink8s-main](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-main/1625117003775741952)
[13/2/2023, 6:28:53 am periodic-cluster-api-e2e-mink8s-main](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-main/1624935553730351104)
[13/2/2023, 4:27:50 am periodic-cluster-api-e2e-mink8s-main](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-main/1624905102022152192)
[12/2/2023, 10:27:52 pm periodic-cluster-api-e2e-mink8s-main](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-main/1624814501217964032)
[12/2/2023, 8:27:04 pm periodic-cluster-api-e2e-mink8s-main](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-main/1624784049681731584)

/kind failing-test

cc @kubernetes-sigs/cluster-api-release-team

**Comment by killianmuldoon** [comment] 2023-02-13 14:08
Thanks for opening this @aniruddha2000! 

/triage accepted

**Comment by sbueringer** [comment] 2023-02-16 18:36
Root cause will be fixed via: https://github.com/kubernetes-sigs/cluster-api/issues/8124

Let's keep this issue until we can verify that the e2e test on main has been stable for a while.

**Comment by sbueringer** [comment] 2023-02-20 13:55
Issue should be fixed for KCP

We have a similar issue with the Cluster topology controller (only affects v1.2 => main and v1.3 => main).

Working on this now.

For now disabling the rollout check to get back to green CI: https://github.com/kubernetes-sigs/cluster-api/pull/8138

**Comment by sbueringer** [comment] 2023-02-21 13:41
Justed merged the fix: https://github.com/kubernetes-sigs/cluster-api/pull/8139

Now this issue shouldn't occur anymore

**Comment by sbueringer** [comment] 2023-02-24 04:37
@aniruddha2000 @furkatgofurov7 I think we can close this issue given that "Machines should remain the same after the upgrade" doesn't occur anymore. I think I would treat other flakes as a new issue.

**Closed** 2023-02-24 08:54 UTC
Labels: kind/failing-test, triage/accepted
