### ISSUE TITLE
Documentation for specifying the single AZ constraint for MachineDeployment

### ISSUE THREAD

**Issue by Ankitasw** [kubernetes-sigs/cluster-api#6045] opened 2022-02-02 06:15 UTC
**What steps did you take and what happened:**
As discussed in [CAPA](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2924) about supporting single AZ for MD, we should consider adding this to our Cluster API book too so as there does not exist any clear warning for the same, and users might use multiAZ for machine deployments.

**What did you expect to happen:**
Clear mention about supporting single AZ for Machine Deployment in Cluster API book.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind documentation

**Comment by killianmuldoon** [comment] 2022-02-02 09:33
#5542 is related to this I think - is that right @Ankitasw?

**Comment by Ankitasw** [comment] 2022-02-02 09:55
@killianmuldoon yes, this can be taken care in failure domains.

**Comment by fabriziopandini** [comment] 2022-02-02 10:15
/close
given this is a duplicate of #5542

**Closed** 2022-02-02 10:16 UTC
Labels: kind/documentation
