### ISSUE TITLE
feature: Formal KCP / CAPBK API to differentiate between init/join phases at bootstrap time

### ISSUE THREAD

**Issue by jdef** [kubernetes-sigs/cluster-api#4838] opened 2021-06-21 15:54 UTC
**User Story**

The current KCP API relies on a single CAPBK config for pre/post steps across all control plane machines, and does not provide a formal API/guarantee to address the need for different pre/post step execution depending on init vs. join phase.

**Detailed Description**

The current implementation doesn't provide a contract for differentiating between init vs. join phase of KCP nodes. At bootstrap time, control plane nodes that wish to execute different pre/post step logic depending on init vs. join phase are forced to use "non-stable" checks to determine phase (e.g. look for `kubeadm.yaml` for init phase, and `kubeadm-join-config.yaml` for join phase).

Either (a) this approach should be formalized, and documented as a supported "feature" of KCP/CAPBK, or else; (b) an alternative API should be provided. The way I see it, there are a couple of approaches that an alternate API could take:

Approach 1, filesystem API: distinguish via sentinel file on the control plane node, CAPBK automatically defines a file (e.g. `/run/capbk-phase/join`) that reflects the phase of the machine.

Approach 2, resource API: some KCP field that allows different configs to be specified for init vs join phases.

Whatever the approach is, ideally it would be simple and small enough to easily backport to CAPI v0.3.x

/kind feature

**Comment by CecileRobertMichon** [comment] 2021-06-21 17:13
duplicate of #3828

**Comment by vincepri** [comment] 2021-07-28 23:31
Closing in favor of #3828

/close

**Closed by vincepri** 2021-07-28 23:31 UTC
Labels: kind/feature
