### ISSUE TITLE
Surprising version using kustomize

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1528] opened 2019-10-14 15:02 UTC
**What steps did you take and what happened:**
Running `kustomize build https://github.com/kubernetes-sigs/cluster-api//config/default?ref=release-0.2` gets YAML that references the `:master` image when I would expect that to reference the `release-0.2` image instead

Note: this may not be a bug and may be a mismatch of my understanding and what is actually happening. This is not a blocker as I can consume the release YAMLs.

/kind bug

**Comment by vincepri** [comment] 2019-10-14 16:07
Duplicate of https://github.com/kubernetes-sigs/cluster-api/issues/1509

/close

**Closed by vincepri** 2019-10-14 16:07 UTC
Labels: kind/bug
