### ISSUE TITLE
[Question] should we support adding roles to worker node ? 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api#881] opened 2019-04-09 08:37 UTC
This actually comes from https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/298
but I think it's applicable to cluster-api 

should we add this into yaml so that user is able to set role during cluster-api creation stage or guide user to change the role after cluster is up? 

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by gyliu513** [comment] 2019-04-09 09:20
/cc @vincepri @detiber 

Thanks @jichenjc , +1 for this.

**Comment by vincepri** [comment] 2019-04-09 18:36
Hopefully the role can be offered, in the fullness of time, as a top level configuration parameter and default to `node` as @detiber mentioned.

**Comment by jichenjc** [comment] 2019-04-10 02:45
@detiber can you tell me where's the place to add role in aws provider? just want to refer to .. thanks

**Comment by jichenjc** [comment] 2019-04-10 02:50
/assign

I can take a look and see how we can achieve this

**Comment by tahsinrahman** [comment] 2019-04-10 03:56
@jichenjc 
- aws: https://github.com/tahsinrahman/cluster-api-provider-aws/blob/50bda8c90faa57a53b4c535136f94e854ab9f5a3/pkg/cloud/aws/services/kubeadm/aws_defaults.go#L170
- azure: https://github.com/tahsinrahman/cluster-api-provider-azure/blob/3734f39b9d0d24eac62fc3a607a5c9fc7ccbaa4b/pkg/cloud/azure/services/config/node.go#L51

**Comment by jichenjc** [comment] 2019-04-10 07:56
@tashimi thanks for the comments ~

**Comment by jichenjc** [comment] 2019-04-19 10:23
#493 seems addressed this issue ...

**Comment by ncdc** [comment] 2019-05-31 15:03
Closing this as a duplicate of #493.
/close

**Closed by ncdc** 2019-05-31 15:03 UTC
Labels: kind/feature, priority/important-soon
