### ISSUE TITLE
KCP Controller Manager fails etcd member checks in certain Azure deployment scenarios

### ISSUE THREAD

**Issue by josh-ferrell** [kubernetes-sigs/cluster-api#6765] opened 2022-06-28 19:18 UTC
**What steps did you take and what happened:**
When the KCP controller manager is running on a control plane node in a self-hosted cluster in Azure the etcd member health checks will fail because of the Azure hairpin issue with Azure LBs until the KCP controller pod is deleted and rescheduled to a worker node 

**What did you expect to happen:**
etcd member health checks succeed when etcd is truly healthy. 

**Anything else you would like to add:**
This was solved by placing a node affinity for non-control plane nodes. Though it doesn't guarantee the correct placement in this scenario it can help to mitigate the frequency of it occurring. The failed etcd member health checks will present to the end user when attempting to roll KCP based on a new AzureMachineTemplate.

**Environment:**

- Cluster-api version: 1.0.1
- minikube/kind version:
- Kubernetes version: (use `kubectl version`): 1.21.x and 1.22.x
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment] 2022-07-04 18:22
The hairpin problem in CAPZ can affect any pod or users doing kubectl proxy, so it is not really a KCP-specific problem, but more a conformance problem.

Going back to KCP we can explore solutions to make it more resilient, but this seems a duplicate of the discussion we are having on #6657

**Comment by fabriziopandini** [comment] 2022-07-29 18:36
/close

https://github.com/kubernetes-sigs/cluster-api/issues/6831 have fixed this

**Closed** 2022-07-29 18:37 UTC
Labels: kind/bug
