### ISSUE TITLE
🐛 condition.lastTransitionTime should be required, right?

### ISSUE THREAD

**Issue by jdef** [kubernetes-sigs/cluster-api#5233] opened 2021-09-13 18:54 UTC
**What steps did you take and what happened:**

Type declaration indicates that "required" is desired:
* https://github.com/kubernetes-sigs/cluster-api/blob/release-0.3/api/v1alpha3/condition_types.go#L75

CRD definition does not take this into account:
* https://github.com/kubernetes-sigs/cluster-api/blob/release-0.3/config/crd/bases/cluster.x-k8s.io_clusters.yaml#L361

**What did you expect to happen:**

I expected the Go type declaration to match the CRD definition. Suspect that the "kubebuilder:validation" prefix was mistakenly left off the Go field declarations (though somehow "status" and "type" are listed as required by the CRD).

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: release-0.3
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment] 2021-09-14 07:18
The problem is the `omitempty` which makes it optional. When we drop it, the field is required.

**Comment by fabriziopandini** [comment] 2021-09-15 10:55
+1 to change this
+1 to audit our API before graduating to v1beta1. Let's open an issue for it

**Comment by sbueringer** [comment] 2021-09-15 11:03
But we will make this field mandatory with v1beta1, right? Because doing this in v1alpha3 or v1alpha4 looks like a breaking change to me.

**Comment by sbueringer** [comment] 2021-09-15 12:41
> +1 to change this
> +1 to audit our API before graduating to v1beta1. Let's open an issue for it

audit Issue: https://github.com/kubernetes-sigs/cluster-api/issues/5239

**Comment by fabriziopandini** [comment] 2021-09-15 13:11
Sure, API breaking changes should go into v1beta1

**Comment by sbueringer** [comment] 2021-09-27 16:06
Fixed in #5303

/close

**Closed** 2021-09-27 16:06 UTC
Labels: kind/bug, area/api
