### ISSUE TITLE
Unbound resource creation within managed topologies

### ISSUE THREAD

**Issue by mnaser** [kubernetes-sigs/cluster-api#10275] opened 2024-03-14 17:58 UTC
### What steps did you take and what happened?

When using managed topologies, we've ran into an issue where if the user creates a `Cluster` with some invalid value that ends up failing validation down the line, CAPI will keep creating resources non-stop.

For example:

```
status:
  conditions:
  - lastTransitionTime: "2024-02-29T14:07:45Z"
    message: 'error reconciling the Cluster topology: failed to create KubeadmControlPlane.controlplane.cluster.x-k8s.io:
      FieldValueForbidden: spec.kubeadmConfigSpec.format: Forbidden: can be set only
      if the KubeadmBootstrapFormatIgnition feature gate is enabled FieldValueForbidden:
      spec.kubeadmConfigSpec.ignition: Forbidden: can be set only if the KubeadmBootstrapFormatIgnition
      feature gate is enabled'
    reason: TopologyReconcileFailed
    severity: Error
    status: "False"
    type: TopologyReconciled
  observedGeneration: 1
  phase: Pending
```

As it keeps trying again and again, it will keep spawning more `InfrastructureCluster` resources, in my case, got up to ~5k and ~11k at some point.

### What did you expect to happen?

CAPI should try and figure out if there is an existing `InfrastructureCluster` tied to this, if there is, then just re-use that instead of creating it again.

### Cluster API version

1.6.0

### Kubernetes version

1.28

### Anything else you would like to add?

Happy to assist to fixing it if we're pointed where to go.

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment] 2024-03-14 18:30
@fabriziopandini could this be a bad edge case around the cluster shim?

**Comment by fabriziopandini** [comment] 2024-03-15 12:45
Yep, I try to reproduce next week

**Comment by fabriziopandini** [comment] 2024-03-18 14:05
/triage accepted
/assign

The issue isn't in the cluster shim, but in the fact that we reconcile the cluster object (with the infrastructure Ref) only if both Infra cluster and control plane are created successfully. This leads the next read desired state to believe there is no infra cluster and thus to re-create it.

I'm going to send a PR to fix this

Note: cluster shim is going to clean up all those objects as soon as both Infra cluster and control plane are reconciled successfully (as per design)

**Comment by fabriziopandini** [comment] 2024-03-18 20:39
@mnaser it will be great if you can help in validating the fix PR

**Comment by chrischdi** [comment] 2024-03-27 09:36
/reopen

Let's close this after cherry-picks to release-1.5 and release-1.6 are done.

**Comment by fabriziopandini** [comment] 2024-03-29 21:34
1.6 backport https://github.com/kubernetes-sigs/cluster-api/pull/10326

**Comment by fabriziopandini** [comment] 2024-03-29 21:38
1.5 backport https://github.com/kubernetes-sigs/cluster-api/pull/10347

**Comment by killianmuldoon** [comment] 2024-04-03 06:00
I think this can now be closed - backports are merged.

**Closed by killianmuldoon** 2024-04-03 06:00 UTC
Labels: kind/bug, triage/accepted
