### ISSUE TITLE
Proposal: Implement the cluster-api-do controller for handling DigitalOcean Kubernetes clusters

### ISSUE THREAD

**Issue by xmudrii** [kubernetes-sigs/cluster-api#211] opened 2018-05-24 17:29 UTC
**Type**: Proposal

It would be nice to have a controller, like for AWS/GCP, for handling cluster creation and managing DigitalOcean Droplets (instances).

I'm willing to work and maintain this one if there is interests for such controller. Let me know is there something else needed to be provided for a proposal.

/kind feature
/cc @kris-nova

**Comment by rsdcastro** [comment] 2018-05-24 17:35
Dupe of https://github.com/kubernetes-sigs/cluster-api/issues/55?

**Closed by rsdcastro** 2018-05-24 17:35 UTC
Labels: kind/feature
