### ISSUE TITLE
 Bad MachineSet prevent all other MachineSets from scaling activities

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api#913] opened 2019-04-24 09:33 UTC
/kind bug

**What steps did you take and what happened:**
1. Create a new MachineSet with a bad label, e.g 
``` template:
    metadata:
      labels:
        cluster.k8s.io/cluster-api-machineset: badmachineset
    spec:
      metadata:
        labels: ssd:"true"
```

2. get controller manager logs to see errors
3. Create a new machineset with correct labels or scale an existing worker machineset and watch nothing happen.
4. Correct or delete the label in badmachineset and everything kicks into gear

**What did you expect to happen:**
The bad machineset would be ignored with no machines created and reasonable error logged. Good and existing machinesets would continue functioning normally. Better yet validation wouldn't even let you create the badmachineset to begin with.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by enxebre** [comment] 2019-04-24 09:34
related https://github.com/kubernetes-sigs/controller-tools/pull/195
cc @ingvagabund

**Comment by ncdc** [comment] 2019-05-31 15:27
@liztio it looks like there has been some movement in kubernetes to address this. Would you have some time to follow the chain of issues & PRs to see if we'll get this fixed for free in newer Kubernetes releases?

**Comment by ncdc** [comment] 2019-08-19 18:48
I am not able to reproduce this with the latest code (master / v1alpha2):

```yaml
apiVersion: cluster.x-k8s.io/v1alpha2
kind: MachineSet
metadata:
  name: badms
spec:
  selector:
    a: b
  template:
    metadata:
      labels: ssd: "true
```

```
k apply -f badms.yaml
error: error parsing badms.yaml: error converting YAML to JSON: yaml: line 10: mapping values are not allowed in this context
```

**Comment by timothysc** [comment] 2019-09-26 18:29
This should be fixed in v1alpha2.

**Closed by timothysc** 2019-09-26 18:29 UTC
Labels: area/machine, kind/bug, priority/important-soon
