### ISSUE TITLE
Reconcile errors in CAPI after updating controllers from v1alpha2 to v1alpha3

### ISSUE THREAD

**Issue by DheerajSShetty** [kubernetes-sigs/cluster-api#3343] opened 2020-07-15 00:23 UTC
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
1. Create a cluster with a controlplane and machinedeployment using a v1alpha2 controller/CRD.
2. Make sure thee cluster comes up fine.
3. Update the controllers/CRDS/Webhhoks to v1alpha3.
4. We see CAPI reconciling with errors
```
E0714 05:45:19.437451       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="retrieved empty dataSecretName from bootstrap provider for Machine \"make-20-controlplane-0\" in namespace \"namespace1\"" "controller"="machine" "name"="make-20-controlplane-0" "namespace"="namespace1"
E0714 05:45:19.678468       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="retrieved empty dataSecretName from bootstrap provider for Machine \"make-18-controlplane-0\" in namespace \"namespace1\"" "controller"="machine" "name"="make-18-controlplane-0" "namespace"="namespace1"
E0714 05:45:23.940991       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="retrieved empty dataSecretName from bootstrap provider for Machine \"make-20-worker-77c4b8d5f-nx2b5\" in namespace \"namespace1\"" "controller"="machine" "name"="make-20-worker-77c4b8d5f-nx2b5" "namespace"="namespace1"
E0714 05:45:24.048114       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="retrieved empty dataSecretName from bootstrap provider for Machine \"make-20-controlplane-1\" in namespace \"namespace1\"" "controller"="machine" "name"="make-20-controlplane-1" "namespace"="namespace1"
E0714 05:45:24.065766       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="retrieved empty dataSecretName from bootstrap provider for Machine \"make-18-worker-7b5f8d7688-h6ptg\" in namespace \"namespace1\"" "controller"="machine" "name"="make-18-worker-7b5f8d7688-h6ptg" "namespace"="namespace1"
E0714 05:45:24.379923       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="retrieved empty dataSecretName from bootstrap provider for Machine \"make-18-worker-7b5f8d7688-xkvjz\" in namespace \"namespace1\"" "controller"="machine" "name"="make-18-worker-7b5f8d7688-xkvjz" "namespace"="namespace1"
E0714 05:45:24.700480       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="retrieved empty dataSecretName from bootstrap provider for Machine \"make-20-controlplane-2\" in namespace \"namespace1\"" "controller"="machine" "name"="make-20-controlplane-2" "namespace"="namespace1"
E0714 05:45:24.700530       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="retrieved empty dataSecretName from bootstrap provider for Machine \"make-20-controlplane-0\" in namespace \"namespace1\"" "controller"="machine" "name"="make-20-controlplane-0" "namespace"="namespace1"
E0714 05:45:24.837066       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="retrieved empty dataSecretName from bootstrap provider for Machine \"make-18-controlplane-0\" in namespace \"namespace1\"" "controller"="machine" "name"="make-18-controlplane-0" "namespace"="namespace1"
```

**What did you expect to happen:**
1. Expected no issues in CAPI.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.3.7-rc.1
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment] 2020-07-15 11:11
I quickly investigated the topic and IMO this is a transient error that gets automatically fixed when the KubeadmConfig object gets reconciled by the CAPBK controller/v1alppha3 for the first time. In fact, I checked in the cluster and now the dataSecretName is correctly set e.g. for `make-20-controlplane-0 `

@vincepri is this correct?

**Comment by vincepri** [comment] 2020-07-15 13:51
That's correct, the error should go away on its own after a while

**Comment by ncdc** [comment] 2020-07-15 15:25
Closing, as this is not a bug.
/close

**Closed** 2020-07-15 15:25 UTC
Labels: kind/bug
