### ISSUE TITLE
Prowjobs fail with `Pod got deleted unexpectedly` on community aws infrastructure

### ISSUE THREAD

**Issue by chrischdi** [kubernetes-sigs/cluster-api#9901] opened 2023-12-19 11:21 UTC
### Which jobs are failing?

Several periodics fail over time.

Failures between 12th December and 19th December 2023 (7days):

* `periodic-cluster-api-e2e-dualstack-and-ipv6-main`: 5 failures the last 7 days (runs every 2h)
* `capi-e2e-main`: 7 failures the last 7 days (runs every 2h)
* `capi-e2e-mink8s-main`: 14 failures the last 7 days (runs every 2h)
* `capi-e2e-main-1-24-1-25`: 1 failure the last 7 days (runs every 24h)
* `capi-e2e-main-1-26-1-27`: 2 failures the last 7 days (runs every 24h)

So for the affected jobs this is a failure rate of ~ 10.9% (`= 29/(3*7*12+2*7`) because of this issue.

### Which tests are failing?

No test or artifacts get reported for the affected job.

### Since when has it been failing?

Started when moving jobs to the community owned AWS infrastructure.

The exact start date is unknown, but this flake seems to be evident since Sept 1st 2023.

### Reason for failure (if possible)

The test job only says:
> `Job execution failed: Pod got deleted unexpectedly`

Example: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-main/1736768378699255808

### Anything else we need to know?

xref original issue where we started to move v1.3 jobs to the community owned AWS infrastructure:

- #9379

> We migrated all nodes in the EKS Prow build cluster to a public subnet, so all nodes have public IP addresses instead of routing all traffic via a NAT Gateway.

Refer to: https://github.com/kubernetes/org/issues/4433#issuecomment-1702713021
Refer to : [kubernetes.slack.com/archives/C8TSNPY4T/p1694020825316969](https://kubernetes.slack.com/archives/C8TSNPY4T/p1694020825316969)

This might be related to the thread going on in #sig-k8s-infra on `Nodes are randomly freezing and failing 🧵`

### Label(s) to be applied

/kind failing-test
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment] 2023-12-19 11:37
@ameukam I think you mentioned that this was investigated again. Any news? :)

**Comment by ameukam** [comment] 2023-12-20 08:50
> @ameukam I think you mentioned that this was investigated again. Any news? :)

We are still looking in to this with the EKS Support team. Will take some time to get the root cause.

**Comment by adilGhaffarDev** [comment] 2024-01-16 07:45
@ameukam any update on this fail? also as @sbueringer asked is there an upstream issue that we can follow.

**Comment by sbueringer** [comment] 2024-03-28 17:59
Does this still happen? (I just keep hearing that it's fixed :))

**Comment by adilGhaffarDev** [comment] 2024-03-28 18:22
> Does this still happen? (I just keep hearing that it's fixed :))

yes, it is fixed, I don't see it on testgrid or on triage board. We can close this issue.

**Comment by fabriziopandini** [comment] 2024-03-29 19:44
/close
As per comment above

**Closed by fabriziopandini** 2024-03-29 19:44 UTC
Labels: kind/failing-test, needs-triage, area/e2e-testing
