### ISSUE TITLE
Provide testing framework to be used across all actuator implementations

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes-sigs/cluster-api#510] opened 2018-09-24 10:27 UTC
To verify each actuator works properly we need to run a series of tests. Some tests require creation of various clients (e.g. to list nodes, machines, etc.) followed by CRUD queries over various resources (see [1], [2] for examples). Would be great to have all the pieces in the main upstream repo so we can together polish and provide testing framework for the current and the future implementations to speed up the CI/CD pipeline.

[1] https://github.com/openshift/cluster-api-provider-aws/blob/master/cmd/aws-actuator/main.go#L309-L357
[2] https://github.com/openshift/machine-api-operator/blob/master/tests/e2e/main.go#L49-L154

**Comment by ingvagabund** [comment] 2018-09-24 10:28
@enxebre @dgoodwin @detiber

**Comment by ingvagabund** [comment] 2018-10-22 11:39
Current e2e framework for aws and libvirt actuator lives at https://github.com/openshift/cluster-api-actuator-pkg. Anyone freel free to reuse it and/or extend it.

**Comment by roberthbailey** [comment] 2019-01-11 20:21
This seems to be the same thing as the conformance tests, so I'm going to close as a dupe of https://github.com/kubernetes-sigs/cluster-api/issues/34.

**Closed by roberthbailey** 2019-01-11 20:21 UTC
