### ISSUE TITLE
nil pointer dereference while the controller cannot find the matching Node for a machine. 

### ISSUE THREAD

**Issue by harishspqr** [kubernetes-sigs/cluster-api#1118] opened 2019-07-03 21:25 UTC
/kind bug

Here are the logs with call stack: 

`I0703 21:01:32.588010       1 noderef_controller.go:84] Reconcile request for Machine "worker-lindic-703f-t2.medium-547557bc47-qkbx4" in namespace "6a8585e7f3657d0d68d189e0ffc2cb7ca093e181"
W0703 21:01:32.674289       1 noderef_controller.go:165] Cannot find a matching Node for Machine "worker-lindic-703f-t2.medium-547557bc47-qkbx4" in namespace "6a8585e7f3657d0d68d189e0ffc2cb7ca093e181", retrying later
E0703 21:01:32.674476       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:522
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/go/src/sigs.k8s.io/cluster-api/pkg/controller/noderef/noderef_controller.go:140
/go/src/sigs.k8s.io/cluster-api/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
/go/src/sigs.k8s.io/cluster-api/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x10ec9df]

goroutine 193 [running]:
sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1209780, 0x207f0a0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
sigs.k8s.io/cluster-api/pkg/controller/noderef.(*ReconcileNodeRef).Reconcile(0xc000460870, 0xc0009140c0, 0x28, 0xc000914090, 0x2d, 0x20930c0, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cluster-api/pkg/controller/noderef/noderef_controller.go:140 +0x8cf
sigs.k8s.io/cluster-api/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003e4e60, 0x0)
	/go/src/sigs.k8s.io/cluster-api/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x1cc
sigs.k8s.io/cluster-api/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	/go/src/sigs.k8s.io/cluster-api/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000a04b80)
	/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a04b80, 0x3b9aca00, 0x0, 0x4554445834424d01, 0xc000358120)
	/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000a04b80, 0x3b9aca00, 0xc000358120)
	/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/cluster-api/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/src/sigs.k8s.io/cluster-api/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x311`

**Comment by vincepri** [comment] 2019-07-03 21:26
Duplicate of #1104

**Comment by detiber** [comment] 2019-07-05 13:35
Closing, since this is a duplicate.

**Closed by detiber** 2019-07-05 13:35 UTC
Labels: kind/bug
