### ISSUE TITLE
Mutability of KubeadmConfigSpec

### ISSUE THREAD

**Issue by Arvinderpal** [kubernetes-sigs/cluster-api#3195] opened 2020-06-15 22:47 UTC
**User Story**

- As a user/operator I would like to have finer control over the kubeadm specific configuration parameters of my cluster. 

- As a user/operator I would like to upgrade my clusters to utilize the latest/cutting-edge features as soon as they are exposed via kubeadm.

- As a developer/user I would like to experiment with different parameters with the understanding that I'm responsible for my own validation and troubleshooting. 

**Detailed Description**

KubeadmControlPlane's `kubeadmConfigSpec`currently [limits](https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go#L92) mutability to a subset of the available parameters. We would like to have a way to bypass/disable this limitation. 

**Anything else you would like to add:**

Related Issues:

- https://github.com/kubernetes-sigs/cluster-api/issues/3014 -- brings mutability to `PreKubeadmCommands`, `PostKubeadmCommands` and `Files` and has been merged. 

- https://github.com/kubernetes-sigs/cluster-api/issues/1584 -- expose `KubeletConfiguration` and `KubeProxyConfiguration`.

/kind feature

**Comment by Arvinderpal** [comment] 2020-06-15 22:47
One approach is to introduce a run-time flag to KCP (e.g. `--enable-expert-mode`) that bypasses these validation checks, and would essentially do the following:

```
allowedPaths := [][]string{
  {"spec", "*"},
  ...
```

**Comment by Arvinderpal** [comment] 2020-06-15 22:49
CC @alanmeadows @sb464f

**Comment by fabriziopandini** [comment] 2020-06-16 09:24
@Arvinderpal IMO this is a duplicate of https://github.com/kubernetes-sigs/cluster-api/issues/2083.
What about closing/dedupe by copying the above comments on this issue?

**Comment by Arvinderpal** [comment] 2020-06-16 13:31
Thanks @fabriziopandini. I'll update the other ticket.
/close

**Closed** 2020-06-16 13:31 UTC
Labels: kind/feature
