### ISSUE TITLE
Question regarding CAPD infrastructure components manifest

### ISSUE THREAD

**Issue by abhay-krishna** [kubernetes-sigs/cluster-api#6972] opened 2022-07-22 19:24 UTC
I downloaded the CAPD manifest linked in the v1.2.0 release and noticed that the image referenced in the Deployment was tagged `main`.
```
$ curl -fsSL https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.0/infrastructure-components-development.yaml | grep image:
        image: gcr.io/k8s-staging-cluster-api/capd-manager:main
```
For previous releases however it is tagged with that tag version
```
$ curl -fsSL https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.5/infrastructure-components-development.yaml | grep image:
        image: gcr.io/k8s-staging-cluster-api/capd-manager:v1.1.5
```

I was wondering if this is intended for every new version that comes out, where the latest CAPD image deployed will be tagged `main`.

**Comment by killianmuldoon** [comment] 2022-07-25 07:34
/assign

Definitely seems like an issue with the latest release.

**Comment by killianmuldoon** [comment] 2022-07-25 08:03
@abhay-krishna Thanks for catching this! The image is published and available so you should change the image in your local manifest to `gcr.io/k8s-staging-cluster-api/capd-manager:main`. I'm going to figure out our options for updating the release with the fixed manifest.

**Comment by killianmuldoon** [comment] 2022-07-25 09:41
This should be fixed in the current release branch, and I've got a PR out to fix the root cause in how our manifests are being generated. Thanks again for catching this!

**Closed** 2022-07-25 10:00 UTC
Labels: area/provider/docker
