### ISSUE TITLE
How to set the values of 'requests' and 'limits' about the CAPI pods 

### ISSUE THREAD

**Issue by ruifaling** [kubernetes-sigs/cluster-api#6959] opened 2022-07-20 03:15 UTC
How to set the values of requests and limits of pod when deploying CAPI? What is the relationship between the size of the workload cluster and CAPI resource consumption ?

**Comment by ruifaling** [comment] 2022-07-20 05:46
kind/help

**Comment by killianmuldoon** [comment] 2022-07-25 12:08
/close 

Duplicate of #1677

**Closed** 2022-07-25 12:08 UTC
