### ISSUE TITLE
clusterctl v0.3.4 not using default config location

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes-sigs/cluster-api#2986] opened 2020-04-29 21:41 UTC
**What steps did you take and what happened:**
I just grabbed the latest `clusterctl`, filled in some values at `~/cluster-api/clusterctl.yaml`, and tried to create a management cluster. Here is what I saw:

```sh
$ clusterctl init --infrastructure vsphere
Fetching providers
Error: failed to get provider components for the "vsphere" provider: failed to perform variable substitution: value for variables [VSPHERE_PASSWORD, VSPHERE_USERNAME] is not set. Please set the value using os environment variables or the clusterctl config file
```

The variables it is complaining about *are* defined, so I figured maybe it wasn't reading it.

Sure enough, this command worked:

```sh
$ clusterctl init --infrastructure vsphere --config .cluster-api/clusterctl.yaml
Fetching providers
Installing cert-manager
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v0.3.4" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v0.3.4" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v0.3.4" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-vsphere" Version="v0.6.3" TargetNamespace="capv-system"

Your management cluster has been initialized successfully!
```

**What did you expect to happen:**

I expected the default config location to be used. The help mentions the location I supplied is already the default:

```sh
Global Flags:
      --config $HOME/.cluster-api/clusterctl.yaml   Path to clusterctl configuration (default is $HOME/.cluster-api/clusterctl.yaml)
```

**Anything else you would like to add:**

**Environment:**

- Cluster-api version: `clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.4", GitCommit:"7cda00b20b09cdccf2ce4e5e952ecfdc0f87ccd5", GitTreeState:"clean", BuildDate:"2020-04-28T23:14:09Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}`
- Minikube/KIND version: 0.7.0
- Kubernetes version: (use `kubectl version`): 1.18.0
- OS (e.g. from `/etc/os-release`): CentOS 7

/kind bug

**Comment by fabriziopandini** [comment] 2020-04-30 07:44
This is a duplicate of https://github.com/kubernetes-sigs/cluster-api/issues/2982 and the problem was fixed by https://github.com/kubernetes-sigs/cluster-api/pull/2983
/close

**Closed by fabriziopandini** 2020-04-30 07:44 UTC
Labels: kind/bug, priority/critical-urgent
