### ISSUE TITLE
Consider moving MachinePool to experimental

### ISSUE THREAD

**Issue by juan-lee** [kubernetes-sigs/cluster-api#2484] opened 2020-02-28 22:21 UTC
**User Story**

As a developer I would like to be able to freely evolve the MachinePool API after v1alpha3 is released due to new requirements around AWS/Azure SPOT support.

**Detailed Description**

Does it make sense for MachinePool to be in an experimental category for some amount of time before being included in the core api? Features like SPOT for AWS and Azure might require some evolution of the MachinePool API. Once we release v1alpha3, API deprecation policies might make it difficult to accommodate change.

/kind feature

**Comment by juan-lee** [comment] 2020-02-28 22:21
@vincepri FYI

**Comment by ncdc** [comment] 2020-02-28 22:23
SGTM, thanks for proposing this.

**Comment by vincepri** [comment] 2020-02-28 22:24
+1 to this change, I think it makes a lot of sense given the nature of these new API types. Let's chat about it at the next community meeting? I'll play around with it and open a PR to move the types, we can then review/merge next week if there is enough consensus. 

/milestone v0.3.0-rc.3
/assign

cc @JoelSpeed, if we want to do the same for MHC?

**Comment by JoelSpeed** [comment] 2020-03-02 11:58
With regards to MHC, I'm not opposed to the idea of moving to an experimental group if that allows the main CRDs within the group to be promoted to beta and eventually GA. This decision, IMO, should be deferred to people with more experience in the project than I have.

That said, I would like to add some context to help the decision. I think the MHC project is a lot smaller than the MachinePool project and is likely to have fewer changes needed to it than MachinePool is likely to need. We introduced MHC into Openshift back in Openshift 4.1 (K8s 1.13) so it has already had some time to mature in our implementation before being ported over to CAPI.  In terms of the API of the MHC, I can't think of anything off the top of my head that will need changing in the mid term, the only problems I'm aware of right now (with the current implementation plans at least) are that MHC doesn't currently support MachinePool (could this need an API change?) and there could be an argument for adding backoff/ratelimiting to MHC. I suspect both of these changes would largely be internal and not API breaking.

@enxebre do you have anything to add on this topic?

**Comment by enxebre** [comment] 2020-03-02 13:21
Just one note, we introduced MHC in OCP 4.3.

Regarding the experimental category for MHC I'm not opposed to that but I agree with @JoelSpeed I wouldn't anticipate any breaking API changes on MHC. The heavy implementation development is already done, plus we are alpha. I'd see this a more suitable case for MHC if we were in an already beta API scenario.

>MHC doesn't currently support MachinePool
I wouldn't expect this to happen as machinePool by design relies on the native provider implementation for managing/scaling/health-checking a pool of instances.

Regarding machines/machineSets, MachinePool and spot instances I would expect incremental changes to happen at the provider API level.

**Comment by vincepri** [comment] 2020-03-04 18:27
/close

Closing now that the PR has been merged

**Closed by vincepri** 2020-03-04 18:27 UTC
Labels: kind/feature
