### ISSUE TITLE
test/infrastructure/docker: Test infra and automation

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1504] opened 2019-10-09 21:15 UTC
After merging CAPD under this repository, we need to add new jobs that only run when CAPD code is changed.

/milestone v0.3.0
/priority important-soon
/help

**Comment by chuckha** [comment] 2019-10-22 20:07
This is what's left of #1543

**Comment by ncdc** [comment] 2019-12-06 17:33
#1837 is a dupe of this but it has more info
/close

**Closed by ncdc** 2019-12-06 17:33 UTC
Labels: help wanted, priority/important-soon
