### ISSUE TITLE
`BeforeClusterUpgrade` and `AfterControlPlaneUpgrade` are getting called multiple times per reconcile

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#6667] opened 2022-06-18 07:15 UTC
**Details:**

If a cluster upgrade is blocked by the `BeforeClusterUpgrade` (or subsequently by the `AfterControlPlaneUpgrade` hook) the reconciler is triggered more than once in quick successions.  

Example: As long as the `BeforeClusterUpgrade` hook returns a hook response with `RetryAfterSeconds` set to `10` the cluster object should be requeued and processed once every ~10 seconds. But the cluster is being processed a couple of times in quick succession before is it reprocessed after 10 seconds.

**What did you expect to happen:**

The cluster object should only be processed once with in the 10 seconds.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 

/area runtime-sdk

**Comment by fabriziopandini** [comment] 2022-06-19 21:07
Note: by design, a hook can be called many times.
If we can mitigate the effects of the many reconcile happening due to other watches, that's ok, but I would not consider this a bug but an improvement.
/remove-kind bug
/kind feature

**Comment by sbueringer** [comment] 2022-06-20 07:32
Agree

I think
> The cluster object should only be processed once with in the 10 seconds.

Is not achievable. We should definitely take a look if we have bugs like the one fixed in your PR, but overall we can't guarantee that we only reconcile once every 10 seconds. There are just to many updates that are absolutely expected on the Cluster CR and on objects of the managed topology.

**Closed** 2022-06-20 08:48 UTC
Labels: kind/feature, area/runtime-sdk
