### ISSUE TITLE
Improve health check for managed cluster

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api#6303] opened 2022-03-16 00:31 UTC
**User Story**

As a user or operator I would like to ensure that after I initialize my managed cluster that it is healthy before I deploy workload cluster(s) so that I don't waste time debugging why my workload cluster(s) is stuck not being provisioned.

**Describe the challenges**
After "successfully" completing `clusterctl init --infrastructure *` I'm personally finding there are various scenarios where the actual management cluster is in an unhealthy state. When you then run `kubectl -f myCapiWorkloadCluster.yaml` the cluster is permanently stuck in the provisioning state.

`kubectl describe clusters` at the end shows it can't provision because control plane is not ready:

```
Status:
  Conditions:
    Last Transition Time:  2022-03-14T05:41:11Z
    Reason:                WaitingForControlPlane
    Severity:              Info
    Status:                False
    Type:                  Ready
    Last Transition Time:  2022-03-14T05:41:11Z
    Message:               Waiting for control plane provider to indicate the control plane has been initialized
    Reason:                WaitingForControlPlaneProviderInitialized
    Severity:              Info
    Status:                False
    Type:                  ControlPlaneInitialized
    Last Transition Time:  2022-03-14T05:41:11Z
    Reason:                WaitingForControlPlane
    Severity:              Info
    Status:                False
    Type:                  ControlPlaneReady
    Last Transition Time:  2022-03-14T05:41:20Z
    Status:                True
    Type:                  InfrastructureReady
  Infrastructure Ready:    true
  Observed Generation:     1
  Phase:                   Provisioning
Events:                    <none>
```

I've seen one recurring scenario pop up in various ways why the managed cluster isn't healthy:
Rancher desktop or other local K8s cluster alternative has issues with the volume mount which happens for the certificates to attach to pods.  The mount never happens, and the management cluster never works.

```
Events:
  Type     Reason       Age                    From               Message
  ----     ------       ----                   ----               -------
  Normal   Scheduled    7m58s                  default-scheduler  Successfully assigned capz-system/capz-nmi-6fn2r to dtzardel9
  Warning  FailedMount  3m39s (x2 over 5m56s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[kubelet-config], unattached volumes=[kubelet-config kube-api-access-s8d42 iptableslock]: timed out waiting for the condition
  Warning  FailedMount  107s (x11 over 7m58s)  kubelet            MountVolume.SetUp failed for volume "kubelet-config" : open /etc/default/kubelet: no such file or directory
  Warning  FailedMount  81s                    kubelet            Unable to attach or mount volumes: unmounted volumes=[kubelet-config], unattached volumes=[iptableslock kubelet-config kube-api-access-s8d42]: timed out waiting for the condition
```

```
  Type     Reason       Age    From               Message
  ----     ------       ----   ----               -------
  Normal   Scheduled    7m50s  default-scheduler  Successfully assigned capi-kubeadm-control-plane-system/capi-kubeadm-control-plane-controller-manager-86c4dcbc4c-zpd7b to docker-desktop
  Warning  FailedMount  7m50s  kubelet            MountVolume.SetUp failed for volume "cert" : secret "capi-kubeadm-control-plane-webhook-service-cert" not found
  Normal   Pulled       7m48s  kubelet            Container image "k8s.gcr.io/cluster-api/kubeadm-control-plane-controller:v1.1.3" already present on machine
  Normal   Created      7m48s  kubelet            Created container manager
  Normal   Started      7m48s  kubelet            Started container manager
  Warning  Unhealthy    7m47s  kubelet            Readiness probe failed: Get "http://10.1.0.166:9440/readyz": dial tcp 10.1.0.166:9440: connect: connection refused
```

**Describe potential solutions you'd like to see**
Any number of ways to ensure that the management cluster is healthy before attempting to deploy a workload cluster.  This could include things like (in no particular order):

1. Doing a cluster health check after the initial install
2. Not letting the pods go into a healthy state until they actually are healthy
3. Separate clusterctl command line option to specifically check health
4. Not allowing someone to try to provision a new cluster until ensuring health on the management cluster.

/kind feature

related issue: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2169

**Comment by fabriziopandini** [comment] 2022-03-16 09:41
/milestone v1.2
/remove-kind feature
/kind support
/priority awaiting-more-evidence

clusterctl allows to wait for providers to be running using the `--wait-providers` flag
as of today, it executes very basic checks that we can eventually improve, but before going down this path it will be interesting to root cause the problem.

Looking at the info attached it seem there is an underlying problem in kubelet/kubernetes leading to failures the volume mount which happens for the certificates to attach to pod.

The error "MountVolume.SetUp failed for volume "cert"  secret "capi-kubeadm-control-plane-webhook-service-cert" not found" hints that cert-manager is not working properly, and in my experience, this is usually due to cluster networking / CNI not working (networking is a precondition for cert-manager to work). I will start investigating this.

Another thing that could be relevant is to check if enough resources (disk/CPU) are allocated or available; so far we are recommending  6Gb for CAPD; lack of resources could explain cert-manager working intermittently

**Comment by dtzar** [comment] 2022-03-16 23:51
@fabriziopandini - that's good to know about the `--wait-providers` flag, but I'm not sure that really would solve this issue.
I solved the problem myself by switching from a freshly installed copy of Rancher Desktop for Windows with K8s via K3s and ContainerD on 1.23.3 (it said install was fully healthy, but I **think** they might not have things working well with volume mount integration) and using Docker Desktop for Windows's K8s as the management cluster. 

I'm not asking for support on these issues I hit.  It's possible I'm only hitting **just** the scenario where the cluster volume mounts are broken with the underlying K8s system for the management cluster, but I'd presume there are other scenarios which could arise in this same bucket.  Bottom line is - how can we ensure the management cluster is fully healthy (the core CAPI _and_ the provider) before allowing people to provision workload clusters without success simply due to the unhealth of the management cluster - ideally by default (i.e. no flag needed).

**Comment by fabriziopandini** [comment] 2022-11-30 21:08
> how can we ensure the management cluster is fully healthy (the core CAPI and the provider) before allowing people to provision workload clusters without success simply due to the unhealth of the management cluster - ideally by default (i.e. no flag needed).

my two cents is that we should improve incrementally, identify one use case that can lead to failures, fix it, and move to the following one.
also interesting the idea to make clusterctl init to wait by default, but IMO we should ask for feedback during the office hours + treat it as a breaking change

/triage accepted
/help

**Comment by fabriziopandini** [comment] 2023-03-24 18:14
(doing some cleanup on old issues without updates)
/close
unfortunately, no one is picking up the task. the thread will remain available for future reference

**Closed by fabriziopandini** 2023-03-24 18:14 UTC
Labels: help wanted, kind/support, priority/awaiting-more-evidence, lifecycle/frozen, triage/accepted
