### ISSUE TITLE
new cloud provider build failed due to no rbac_role.yaml

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api#781] opened 2019-02-27 06:03 UTC
/kind bug

**What steps did you take and what happened:**
I was following the steps here https://kubernetes-sigs.github.io/cluster-api/provider_implementations/building_running_and_testing.html to build a new cloud provider named as `genesis`, but the build failed at last due to no `rbac_role.yaml`, any comments what is wrong with my steps?

```
root@gyliu-dev1:~/go/src/sigs.k8s.io/cluster-api-provider-genesis# make
go generate ./pkg/... ./cmd/...
go fmt ./pkg/... ./cmd/...
pkg/cloud/genesis/actuators/cluster/actuator.go
pkg/cloud/genesis/actuators/machine/actuator.go
pkg/controller/add_cluster_controller.go
pkg/controller/add_machine_controller.go
cmd/manager/main.go
go vet ./pkg/... ./cmd/...
go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go crd
CRD files generated, files can be found under path /root/go/src/sigs.k8s.io/cluster-api-provider-genesis/config/crds.
kustomize build config/default/ > provider-components.yaml
Error: loadResMapFromBasesAndResources: rawResources failed to read Resources: Load from path ../rbac/rbac_role.yaml failed: open /root/go/src/sigs.k8s.io/cluster-api-provider-genesis/config/rbac/rbac_role.yaml: no such file or directory


Makefile:29: recipe for target 'manifests' failed
```

```
root@gyliu-dev1:~/go/src/sigs.k8s.io/cluster-api-provider-genesis# kubebuilder version
Version: version.Version{KubeBuilderVersion:"1.0.4", KubernetesVendor:"1.11", GitCommit:"f954dc7cff7e6c94d54139f936bb9d42314ad63e", BuildDate:"2018-09-11T21:08:31Z", GoOs:"unknown", GoArch:"unknown"}
```
```
root@gyliu-dev1:~/go/src/sigs.k8s.io/cluster-api-provider-genesis# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1+icp-ee", GitCommit:"5803c3b1f9422c43a963e0610b3a4cad565e127e", GitTreeState:"clean", BuildDate:"2018-09-04T09:29:02Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

FYI @xunpan 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by gyliu513** [comment] 2019-02-27 06:51
Fixede, seems the minimum `kubebuilder` should be v1.0.6

**Comment by yuyangbj** [comment] 2019-02-27 15:37
Please refer to issue #783

**Comment by roberthbailey** [comment] 2019-02-27 18:36
I'm going to close this as a duplicate of #783 since it seems like the same issue. 

/close

**Closed by roberthbailey** 2019-02-27 18:36 UTC
Labels: kind/bug
