### ISSUE TITLE
etcd health check does not return the error 

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api#3519] opened 2020-08-23 03:53 UTC
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

If ectd is not healthy or the client cannot connect properly an error occurs but the error is not propagated up to the event (nil is returned):

```
kubectl describe kubeadmcontrolplanes.controlplane.cluster.x-k8s.io 
Events:                                
Type     Reason                 Age                      From                              Message
  ----     ------                 ----                     ----                              -------                                                                             
 Warning  ControlPlaneUnhealthy  3m32s (x785 over 5h47m)  kubeadm-control-plane-controller  Waiting for control plane to
 pass etcd health check to continue reconciliation: <nil>    
```

**What did you expect to happen:**
The error from etcd to be propogated

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The error is overwritten here:

https://github.com/kubernetes-sigs/cluster-api/blob/b8fdef664b7648df7fdb4ebb23c7efa7aae0a8a6/controlplane/kubeadm/controllers/controller.go#L436-L449

**Environment:**

- Cluster-api version: v0.3.8
- Minikube/KIND version: 
- Kubernetes version: (use `kubectl version`): 1.18.8
- OS (e.g. from `/etc/os-release`): 

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment] 2020-08-24 09:36
@jsturtevant thanks for reporting.
TBH I'm a little bit debated about this, because etcd not reporting normally is a transient state that is part of the startup sequence, and so returning an error probably isn't the best strategy here, but I leave this open for discussion.

However, I agree we should provide more visibility on what is going on and https://github.com/kubernetes-sigs/cluster-api/issues/3138 already goes in that direction

**Comment by benmoss** [comment] 2020-08-26 14:23
I think this is intended behavior from https://github.com/kubernetes-sigs/cluster-api/pull/2841, maybe @sedefsavas can comment

**Comment by sedefsavas** [comment] 2020-08-26 18:07
I agree @fabriziopandini on this, it is a transient error, the only important error here is the one we are logging: `Failed attempt to remove potential hanging etcd members`.
One other thing is we do not use events consistently, maybe it is a good idea to remove them all and either log or use conditions to show errors.

**Comment by vincepri** [comment] 2020-08-26 19:26
Related to https://github.com/kubernetes-sigs/cluster-api/pull/3336 as well

**Comment by vincepri** [comment] 2020-09-02 16:51
The related PR was merged, closing

/close

**Comment by CecileRobertMichon** [comment] 2020-09-02 16:52
/close

#3336 partially addressed this

**Closed** 2020-09-02 16:52 UTC
Labels: kind/bug
