### ISSUE TITLE
Update tests from 1.21 => main are failing

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#4619] opened 2021-05-14 17:44 UTC
**What steps did you take and what happened:**

The update test from 1.21 to latest main is failing since about May 11th. We discovered this through: https://github.com/kubernetes-sigs/cluster-api/pull/4614 .
Testgrid provides some additional data: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main-1-21-latest

**What did you expect to happen:**
Update test should work

**Anything else you would like to add:**

Some details:
* kubeadm control plane controller logs:
```bash
E0513 17:47:30.515474       1 controller.go:302] controller-runtime/manager/controller/kubeadmcontrolplane "msg"="Reconciler error" "error"="failed to update api server in the kubeadm config map: unable to decode \"ClusterConfiguration\" in the kubeadm-config ConfigMap's from YAML: unknown kubeadm types" "name"="k8s-upgrade-and-conformance-8wpt31-control-plane" "namespace"="k8s-upgrade-and-conformance-5qnphx" "reconciler group"="controlplane.cluster.x-k8s.io" "reconciler kind"="KubeadmControlPlane" 
```
https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-workload-upgrade-1-21-latest-main/1392893250792067072/artifacts/clusters/bootstrap/controllers/capi-kubeadm-control-plane-controller-manager/capi-kubeadm-control-plane-controller-manager-6b54c76ff9-djslk/manager.log

I suspect it's been caused by: https://github.com/kubernetes-sigs/cluster-api/commit/5c19ea1f6099e68539146aa40a7631bda618c6c1

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment] 2021-05-14 17:49
/assign 
I will take at look at this

**Comment by fabriziopandini** [comment] 2021-05-17 09:32
Thinks a changed a little bit during this days so:
- A new Kubernetes release was issued v1.21.1
- Kind images for the above version was generated, requiring us to ping the cgroup drivers (Addressed by https://github.com/kubernetes-sigs/cluster-api/pull/4614)

However, the root cause of the problem is kubeadm having switched to v1beta3, while CAPI is lagging behind.
I have pinged @davideimola for https://github.com/kubernetes-sigs/cluster-api/issues/4445; If we don't get answers I will step in so we can restore out test signal

**Closed** 2021-07-06 17:50 UTC
Labels: kind/bug
